# version: '3'
#services:
#  mysql-db:
#    image: mysql:latest
#    container_name: mysql-db
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=achatdb
#    networks:
#      - my-network

#  spring-boot-app:
#    image: faraharbi/springboot-devops
#    container_name: back_springboot_c
#    ports:
#      - "8089:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      - mysql-db
#    networks:
#      - my-network

#  angular-app:
#    image: faraharbi/angular-devops
#    container_name: front_angular_c
#    ports:
#      - "4200:80"
#    depends_on:
#      - spring-boot-app
#    networks:
#      - my-network

networks:
  my-network:
